### ISSUE TITLE
Tracking

### ISSUE THREAD

**Issue by sumobi** [pippinsplugins/rcp-site-child#12]
We should add tracking to the purchase links so we know who came from the new RCP site.

**Comment by pippinsplugins** [comment]
This is pretty simple to do.

Would it be helpful for you if I wrote a simple boolean function called `came_from_rcp()` that you can use on pippinsplugins.com to modify some pages?

**Comment by sumobi** [comment]
@pippinsplugins I was just thinking of using Google UTM links, what did you have in mind, a query string? Then on pp.com we can detect the query string and store it in purchase session + add a note to the purchase? Would be great to see how well the RCP site is redirecting users.

**Comment by pippinsplugins** [comment]
Right, the helper function could just look at the query strings.

**Comment by sumobi** [comment]
The pricing links now include a `referrer=rcp_site` query string which we can use for this, as well as #13

**Comment by sumobi** [comment]
@pippinsplugins look ok to you?

https://github.com/pippinsplugins/pippinsplugins-custom-functions/commit/6b3818cc0da9fb0913705cba3bd629eb2581f94e

storing variable in session if the query string was used (just in case they move around the site, they might even purchase something else) and then storing payment meta.

How do you want to show this in reporting so that we can easily see what percentage of purchases came from the RCP site?

**Comment by pippinsplugins** [comment]
That looks fine.

We could easily build a custom report / view to show all purchases from the rcp site.

**Comment by sumobi** [comment]
:+1:

**Comment by sumobi** [comment]
- [ ]  build a custom report / view to show all purchases from the rcp site.

**Comment by pippinsplugins** [comment]
I've added our Campaign Tracker extension and updated the purchase links with campaign variables.
