### ISSUE TITLE
Show banner on PippinsPlugins.com if user arrives from RCP site

### ISSUE THREAD

**Issue by sumobi** [pippinsplugins/rcp-site-child#13]
How about a banner on the PP.com checkout page if the user clicked a purchase link from the RCP site? Something like "You've just arrived from Restrict Content Pro, complete your purchase below". I think this will help a lot with the transition between the sites.

**Comment by pippinsplugins** [comment]
Yes

**Comment by sumobi** [comment]
Here's what the banner looks like:

![screen shot 2015-10-04 at 6 33 24 pm](https://cloud.githubusercontent.com/assets/52581/10266520/7466b2aa-6ac6-11e5-874d-5618a965e93b.png)

**Comment by pippinsplugins** [comment]
Looks good

**Comment by sumobi** [comment]
:+1:
