### ISSUE TITLE
Viewing homepage screenshots takes you to top of page

### ISSUE THREAD

**Issue by mindctrl** [pippinsplugins/rcp-site-child#14]
If you click a screenshot on the homepage, you get scrolled back to the top. When you close the screenshot you have to scroll back down to where you were to continue reading the features.

![image](https://cloud.githubusercontent.com/assets/1254870/10180539/0df53e80-66dc-11e5-9aaa-dba35512fbfb.png)

- Click one, then close it. You end up here.

![image](https://cloud.githubusercontent.com/assets/1254870/10180551/22e3e3e6-66dc-11e5-9375-528fac7675d5.png)

**Comment by sumobi** [comment]
@mindctrl good spotting, thanks!

**Comment by sumobi** [comment]
Happens on the main screenshots page also. Seems to be caused when a theme has a 100% height applied to the `body` (which I need).

**Comment by sumobi** [comment]
Fixed via https://github.com/pippinsplugins/rcp-site-parent/commit/bd3a021fe05a9aab4ad6779dd61c162b61703c26

Applied a CSS class when the carousel is opened which sets the body height to auto, and then removing it when the carousel is closed.
