### ISSUE TITLE
Consultants page

### ISSUE THREAD

**Issue by pippinsplugins** [pippinsplugins/rcp-site-child#15]
We'll need a consultants page.

I'll add people to it once created.

**Comment by pippinsplugins** [comment]
https://secure.helpscout.net/conversation/127148823/18104/

**Comment by sumobi** [comment]
:+1: For now we can simply list them out. Once we get a few we can add a form similar to AffiliateWP that emails all consultants in one go.

I don't see this as a main navigation link. How about a sub-menu item under "support"? or a simple link in the footer somewhere.

**Comment by sumobi** [comment]
@pippinsplugins new consultants page (though not yet linked from anywhere) http://s12407.p27.sites.pressdns.com/consultants/

**Comment by pippinsplugins** [comment]
Could you add / style a bullet point list? That's most likely how we'll add them

**Comment by sumobi** [comment]
This should do:

![screen shot 2015-10-05 at 4 11 26 pm](https://cloud.githubusercontent.com/assets/52581/10272420/c1a21496-6b7b-11e5-8615-6ab067039b24.png)

**Comment by pippinsplugins** [comment]
:+1:

**Comment by sumobi** [comment]
Added the first consultant, removed the bullet list for now since there's only one:

![screen shot 2015-10-12 at 9 59 04 pm](https://cloud.githubusercontent.com/assets/52581/10424554/791da7a6-712c-11e5-9145-d44cc6581679.png)
