### ISSUE TITLE
Add testimonials

### ISSUE THREAD

**Issue by sumobi** [pippinsplugins/rcp-site-child#2]
We need to source some testimonials to display on the site. @pippinsplugins know anyone/have any? Your brother might have some nice words to say!

**Comment by pippinsplugins** [comment]
From `Chris Lema`

>>> When it comes to a fast and clean membership site, nothing is faster for end users than RCP. When it comes to extensible code that a developer will love, nothing is better than Pippin’s code.

**Comment by pippinsplugins** [comment]
@sumobi 

![screen shot 2015-10-02 at 11 40 52 am](https://cloud.githubusercontent.com/assets/1034109/10252019/77e26f6e-68fa-11e5-80f9-481db142e838.png)

Thoughts?

**Comment by sumobi** [comment]
@pippinsplugins I agree, we do that on the AffWP site also, will change. Something to a/b test in the future perhaps?

**Comment by sumobi** [comment]
Since we only have 1 so far:

![screen shot 2015-10-03 at 6 28 42 pm](https://cloud.githubusercontent.com/assets/52581/10261609/a2df801e-69fc-11e5-8a66-bc2896432ce8.png)

Can expand to 3 nicely when we get more.

**Comment by pippinsplugins** [comment]
@sumobi What about testimonials that don't have a photo to go with them?

**Comment by sumobi** [comment]
I think we should feature 1-3 testimonials with an image (research suggests testimonials with images work better), the rest can exist on a dedicated page with or without images. Ideally I think we should aim to get an image with each, or list all testimonials with photos first, then those that don't have one underneath.

**Comment by pippinsplugins** [comment]
From `Travis Northcutt` of `The Bright Agency`:

>>>RCP is always at the top of my list when helping clients choose a membership platform. In addition to being a great plugin ​_today_​, the pace of improvement is impressive. RCP gets better and better all the time.

**Comment by sumobi** [comment]
:+1: @pippinsplugins could we get a shoulder-up photo?

**Comment by tnorthcutt** [comment]
So, I honestly can't find a pic that's just me and isn't a bit goofy... if you need a serious one, lemme know. Otherwise how's this?

![img_3537](https://cloud.githubusercontent.com/assets/796639/10335583/13ceea88-6cf2-11e5-814f-9e9b253bac9f.jpg)

**Comment by sumobi** [comment]
@tnorthcutt Goofy is fine by me unless @pippinsplugins disagrees. Do you happen to have one that has both shoulders? So I can cut you off at the shoulders like the other pic.

**Comment by pippinsplugins** [comment]
I'm fine with goofy.

**Comment by tnorthcutt** [comment]
Only shoulders one I could find is not goofy. So sad. :frowning: 

![headshot](https://cloud.githubusercontent.com/assets/796639/10348091/52e21c82-6d37-11e5-98bb-853ca8141666.jpg)

**Comment by sumobi** [comment]
@tnorthcutt Perfect :+1:

**Comment by sumobi** [comment]
Anddd we're good to go for now

![screen shot 2015-10-08 at 10 10 36 pm](https://cloud.githubusercontent.com/assets/52581/10362184/7901f82e-6e09-11e5-87ff-35a37e58671e.png)
