### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by mindctrl** [pippinsplugins/rcp-site-child#20]
Need some screenshots of what people see when access to content is restricted. Showing the whole flow from a end user perspective of what they see when it's restricted, how they sign up, what it looks like afterwards, etc. would help illustrate to potential RCP buyers what their customers will see. pippinsplugins.com would make a good example of this flow, and the shots would be more attractive because the theme there is so nice compared to the Twenty * themes.

![image](https://cloud.githubusercontent.com/assets/1254870/10252206/f84cbaf2-6903-11e5-89cb-a73f6d13b595.png)

Also it would be great to equalize the screenshot thumbnails on the screenshots page to make it a little cleaner.

**Comment by sumobi** [comment]
@mindctrl :+1: good points. 

Instead of having 1 large grid of screenshots, how about we split the galleries up into sections with headings to make it easier to scan. "Sign Up", "Admin", "Restricted Access", etc with sub headings that explain what the set of images they are about to view are.

I like the idea of showing screenshots for multiple themes, since a common question with any plugin is always "will it work with my theme?" 

I'd like to do 2016, since it will get used a tonne, and perhaps another theme. I was actually thinking on using the theme that's being used for the RCP site since that will look nice with RCP.

**Comment by mindctrl** [comment]
@sumobi ooh yeah I dig those ideas. :metal:

**Comment by sumobi** [comment]
All screenshots should also have proper titles/captions etc

**Comment by sumobi** [comment]
We should add a call to action button at the bottom of the screenshots page, similar to AffiliateWP. The screenshot page on AffiliateWP is consistently the 3rd most viewed page.

**Comment by sumobi** [comment]
I'm about to start the long process of taking screenshots, grouping them into sections, and showing the 2015 theme. Some of the screenshots are showing an old WordPress version so I'd like to get those updated. There's also a lot more screenshots that we can show. Wish me luck...

**Comment by sumobi** [comment]
First section progress with captions and equal thumbnail sizes

![screen shot 2015-10-04 at 11 23 53 pm](https://cloud.githubusercontent.com/assets/52581/10267402/3b7be806-6aef-11e5-810f-befa590b6b47.png)

Lightbox with helpful title (no more screenshot 85483918232-0345738454.png):

![screen shot 2015-10-04 at 11 24 07 pm](https://cloud.githubusercontent.com/assets/52581/10267401/3b7b68e0-6aef-11e5-8a75-f8ffc02bd477.png)

**Comment by pippinsplugins** [comment]
Excellent!

**Comment by sumobi** [comment]
I think I've finished all the front-end screenshots, 14 in total so far. Moving to admin screens.

![screen shot 2015-10-06 at 12 28 15 am](https://cloud.githubusercontent.com/assets/52581/10279320/2e2e6444-6bc1-11e5-87f2-7fa133afaf53.png)

**Comment by pippinsplugins** [comment]
Those are looking great!

**Comment by sumobi** [comment]
I think I have enough now, closing. @pippinsplugins let me know if there's any more you'd like to see

**Comment by pippinsplugins** [comment]
@sumobi This screenshot isn't really correct (bug in plugin): https://cloudup.com/cvhvIX6wr1c

Instead of pending, it should show expired. You can manually change a member to expired to screenshot it.

**Comment by pippinsplugins** [comment]
Probably best to show one where the member is active and one where they are expired.

**Comment by pippinsplugins** [comment]
Also please move the login form screenshot to just before the forgot password: https://cloudup.com/c_PHy3bor34 - That way when people right-arrow through the screenshots, it shows in the proper order.

**Comment by sumobi** [comment]
@pippinsplugins Now showing a free, active, and expired membership details page. Moved forgot password form.
