### ISSUE TITLE
Launch

### ISSUE THREAD

**Issue by sumobi** [pippinsplugins/rcp-site-child#22]
@pippinsplugins Minus the screenshots (which are coming) do you want to soft-launch this week? Anything else you can see that needs work?

**Comment by pippinsplugins** [comment]
Let's try and make it happen! Let's plan for Thursday.

**Comment by sumobi** [comment]
Woot

**Comment by sumobi** [comment]
@pippinsplugins it's launch day!

**Comment by pippinsplugins** [comment]
URL redirect has been disabled. It should be live shortly.

**Comment by pippinsplugins** [comment]
DNS is updated but getting a 400 bad request on pagely. Not sure why yet.
