### ISSUE TITLE
Footer links

### ISSUE THREAD

**Issue by sumobi** [pippinsplugins/rcp-site-child#24]
We'll need some kind of footer menu to put links like "consultants", potentially brand assets and other links.

**Comment by pippinsplugins** [comment]
- Brand assets
- Twitter
- Refund policy
- Support
- Documentation
- About
- Consultants
- Pippins Plugins
- AffiliateWP
- Easy Digital Downloads

Those are the ones I can think of.

**Comment by sumobi** [comment]
:+1:

**Comment by pippinsplugins** [comment]
Oh, also need changelog.

**Comment by pippinsplugins** [comment]
I'd like an RSS feed from pippinsplugins included

**Comment by sumobi** [comment]
@pippinsplugins how does this look to you:

![screen shot 2015-10-11 at 4 53 13 pm](https://cloud.githubusercontent.com/assets/52581/10414594/97b829ba-7038-11e5-98f4-217e8ee67681.png)

Other links that will be included in the far left column will be:

- Testimonials (dedicated page)
- Brand Assets

I thought it would be a good idea to show the main documentation categories from http://docs.pippinsplugins.com/ in the "quick help" column.

**Comment by sumobi** [comment]
Oh yeah and the changelog opens up nicely in a modal window thanks to wp_remote_get()

![screen shot 2015-10-11 at 5 33 57 pm](https://cloud.githubusercontent.com/assets/52581/10414698/56fcd3c0-703e-11e5-983c-7fb54c43c58e.png)

**Comment by sumobi** [comment]
Mobile goodness

![screen shot 2015-10-11 at 5 35 01 pm](https://cloud.githubusercontent.com/assets/52581/10414701/7aa033ee-703e-11e5-962a-095e7c57fa82.png)

___

![screen shot 2015-10-11 at 5 35 17 pm](https://cloud.githubusercontent.com/assets/52581/10414703/80eafe3c-703e-11e5-8e9c-c1c5f7ef7976.png)

**Comment by pippinsplugins** [comment]
Looks great!

**Comment by sumobi** [comment]
@pippinsplugins will push live soon then :+1:

**Comment by pippinsplugins** [comment]
Woot!

**Comment by sumobi** [comment]
@pippinsplugins It's live!

**Comment by pippinsplugins** [comment]
yay!
