### ISSUE TITLE
Links to documentation

### ISSUE THREAD

**Issue by pippinsplugins** [pippinsplugins/rcp-site-child#28]
The documentation site should have links to it in the footer ( #24 ) and also on the support page: https://cloudup.com/cfj2QjqcKGt

**Comment by sumobi** [comment]
@pippinsplugins So a link to the support page from the HelpScout documentation and vice versa?

**Comment by pippinsplugins** [comment]
Yes

**Comment by sumobi** [comment]
@pippinsplugins Added link to doc on our support page.

![screen shot 2015-10-12 at 9 52 07 pm](https://cloud.githubusercontent.com/assets/52581/10424416/83cb3ec6-712b-11e5-999e-5052b795a073.png)

Added doc to HS

![screen shot 2015-10-12 at 9 51 35 pm](https://cloud.githubusercontent.com/assets/52581/10424409/76d4798a-712b-11e5-968d-4289d893d70b.png)

**Comment by pippinsplugins** [comment]
:+1:
