### ISSUE TITLE
Make placeholder image for add-ons

### ISSUE THREAD

**Issue by pippinsplugins** [pippinsplugins/rcp-site-child#29]
Not all add-ons will be able to have nice images so we should have a decent place holder image for those that is automatically shown if no featured image is set.

**Comment by sumobi** [comment]
:+1: I'll put something together

**Comment by sumobi** [comment]
![screen shot 2015-10-10 at 1 18 55 pm](https://cloud.githubusercontent.com/assets/52581/10408080/7e8d3f8a-6f51-11e5-9d60-f377fd8fdbb5.png)

**Comment by pippinsplugins** [comment]
Love it
