### ISSUE TITLE
Pricing page faqs

### ISSUE THREAD

**Issue by sumobi** [pippinsplugins/rcp-site-child#3]
We need to add some faqs to the main pricing page, similar to AffWP

**Comment by pippinsplugins** [comment]
Points to add:

1. Do I need to renew my license?

Your license key is valid for one year from the purchase date. You need an active license key for continued access to automatic updates and support. If you renew your license each year you’ll receive a huge 40% discount off the current price!

2. Do you have a refund policy?

Yes we do! We stand behind the quality of our product and will refund 100% of your money if you are unhappy with the plugin.

3. Do I get updates for the plugin?

Yes! Automatic updates are available free of charge to all users with a valid license key.

4. Can I upgrade my single-site license?

Yes, you can easily upgrade your license from your account page at anytime.

5. Do you offer support if I need help?

Yes! Top-notch customer support is key for a quality product, so we’ll do our very best to resolve any issues you encounter via our support page.

6. I have other pre-sale questions, can you help?

Yes! You can ask us any question through our support page.

7. Will Restrict Content Pro work on WordPress.com?

No, Restrict Content Pro will not work on WordPress.com. It only works on self-hosted WordPress installs.

8. Does Restrict Content Pro support dripped-content?

No, Restrict Content Pro does not support dripped content at this time.

**Comment by sumobi** [comment]
:+1:

**Comment by sumobi** [comment]
Closed via https://github.com/pippinsplugins/rcp-site-child/commit/c1de75bf4b2a8f44dd43c91cf035473a07a6ec07
