### ISSUE TITLE
Fix color flash

### ISSUE THREAD

**Issue by sumobi** [pippinsplugins/rcp-site-child#30]
When a user is served the purple color variation they will briefly see a flash of green on each page where there are buttons etc before it switches to purple.

**Comment by sumobi** [comment]
@pippinsplugins When you're ready, make each variation have either a `green` or `purple` body tag (alt is no more). And here's the branch to push https://github.com/pippinsplugins/rcp-site-child/tree/issue/30

**Comment by pippinsplugins** [comment]
Looks like the CSS isn't working: https://cloudup.com/ciaF132u7QJ

**Comment by pippinsplugins** [comment]
Green class: https://cloudup.com/cZltoZL5z6a

**Comment by sumobi** [comment]
closing this since I can't think of a way to fix without losing the colors altogether when JS is not enabled.
