### ISSUE TITLE
Buttons don't show up in Chrome and Safari

### ISSUE THREAD

**Issue by mindctrl** [pippinsplugins/rcp-site-child#32]
Tested in both browsers, both are latest versions.

![image](https://cloud.githubusercontent.com/assets/1254870/10611786/a993e70c-771b-11e5-81f4-2012a998f802.png)
--------
![image](https://cloud.githubusercontent.com/assets/1254870/10611790/ae80e9d6-771b-11e5-9145-37f30dce3e36.png)
---------
The buttons have a transparent background, I'm guessing related to the svg. I'm getting 'canceled' errors in the console when loading the svg.
![image](https://cloud.githubusercontent.com/assets/1254870/10611822/e7d6dc18-771b-11e5-84c2-f5499aa278ab.png)

@sumobi ping

**Comment by sumobi** [comment]
@mindctrl Thanks. Weird, works fine here, is it all buttons/svgs on the site? the buttons start off as transparent because of the A/B test but should change to either purple or green. Does clearing the browser cache help at all? @pippinsplugins do you see the same thing?

**Comment by pippinsplugins** [comment]
I can't replicate it.

**Comment by mindctrl** [comment]
@sumobi doh, just realized my browser is blocking Optimizely. That's why it doesn't show up. Can just close this up unless you want some kind of fallback for that (which I'm guessing causes a color flash). Edge case.

**Comment by sumobi** [comment]
@mindctrl is it just blocking Optimizely or a range of sites? is it a browser extension? There's a fallback for no JS (goes green which still causes the color flash)

**Comment by mindctrl** [comment]
@sumobi using Ghostery. If I allow Optimizely, the buttons show. Otherwise they stay transparent.

![image](https://cloud.githubusercontent.com/assets/1254870/10620263/12c26d62-7748-11e5-817a-88b4f1b24b21.png)

---------

![image](https://cloud.githubusercontent.com/assets/1254870/10620271/2047600a-7748-11e5-851f-22d292f92bcd.png)

**Comment by sumobi** [comment]
Ahh cool thanks. Don't think I'll spend time trying to fix this since its very edge case as you said, I'd need to somehow detect if Optimizely is being blocked which I don't think a lot of people are doing. Good to know though. Why you hating on optimizely? :)

**Comment by mindctrl** [comment]
I run into sites from time to time that I need to disable it or allow certain things in. For some reason this time I didn't even think about it. I was too busy tripping on the console message. Most people running blocking software know it can sometimes cause issues, and in that case I think they'll know what to do. Sorry for the distraction here. Didn't mean to run you down a rabbit hole.

**Comment by sumobi** [comment]
No worries at all!
