### ISSUE TITLE
Blog page

### ISSUE THREAD

**Issue by pippinsplugins** [pippinsplugins/rcp-site-child#34]
We need one very soon.

**Comment by sumobi** [comment]
:+1:

**Comment by sumobi** [comment]
Just have to style some comments and i think we'll be good to go

**Comment by pippinsplugins** [comment]
:+1:

**Comment by sumobi** [comment]
@pippinsplugins Blog is good to go. Want to add your first blog as a draft and check things out? I've set up 2 new pages, home and blog, and set blog page as the one that will show the posts.
