### ISSUE TITLE
About page

### ISSUE THREAD

**Issue by sumobi** [pippinsplugins/rcp-site-child#4]
We need some original text for the about page

**Comment by pippinsplugins** [comment]
Do you want about me or about the plugin?

**Comment by sumobi** [comment]
How about both? I'd certainly like to know who built it and why

**Comment by pippinsplugins** [comment]
:+1:

**Comment by sumobi** [comment]
@pippinsplugins You were too slow so I got @wordmaid to write one up:
http://s12407.p27.sites.pressdns.com/about/

**Comment by pippinsplugins** [comment]
@sumobi Let's be honest: that's 10x better than anything I would have written anyhow. Thanks @wordmaid!

**Comment by wordmaid** [comment]
:+1: Pleasure!
