### ISSUE TITLE
Add RCP add-ons

### ISSUE THREAD

**Issue by sumobi** [pippinsplugins/rcp-site-child#6]
Each add-on will need to be added to the site

**Comment by pippinsplugins** [comment]
I want to also create a page (maybe not for v1) for people to submit their add-on. I don't intend to sell 3rd party add-ons, but I want to list them. That also means we need to have an official and 3rd party section, just like AffWP

**Comment by sumobi** [comment]
That's right :+1:

**Comment by sumobi** [comment]
This is what the download sidebar will look like. Has the developer name and link for 3rd party add-ons:

![screen shot 2015-07-30 at 9 27 26 am](https://cloud.githubusercontent.com/assets/52581/8970334/4e7bd7d0-369d-11e5-9fed-fc5692f58673.png)

**Comment by pippinsplugins** [comment]
Great!

**Comment by sumobi** [comment]
Here's the "official" and "3rd party" downloads: http://s12407.p27.sites.pressdns.com/add-ons/. Just 2 [downloads] shortcodes with a category specified.

**Comment by pippinsplugins** [comment]
I like it.

**Comment by sumobi** [comment]
Note, the add-ons page's responsiveness will be busted until EDD 2.5 is released: https://github.com/easydigitaldownloads/Easy-Digital-Downloads/issues/3489

**Comment by pippinsplugins** [comment]
:+1:

**Comment by sumobi** [comment]
Since we're aiming to launch this week I've edited the shortcodes.php file directly to remove the inline styles. This fixes the download grid as mentioned above.

**Comment by pippinsplugins** [comment]
:+1:
