### ISSUE TITLE
Birth a site mascot

### ISSUE THREAD

**Issue by sumobi** [pippinsplugins/rcp-site-child#7]
A "nice to have". @pippinsplugins any progress on the RCP monster?

**Comment by pippinsplugins** [comment]
Tim said he's working on it.

**Comment by sumobi** [comment]
birthing is coming along fantastic on this one

**Comment by pippinsplugins** [comment]
:D

**Comment by sumobi** [comment]
@pippinsplugins any word on the final mascot? will need it with a transparent background layer

**Comment by pippinsplugins** [comment]
Just emailed TIm.

**Comment by pippinsplugins** [comment]
Done and done.
