### ISSUE TITLE
Homepage features

### ISSUE THREAD

**Issue by sumobi** [pippinsplugins/rcp-site-child#8]
The features on the homepage need copy. Now would be a good time to review what the most important features/benefits of RCP are that makes it stand out.

![screen shot 2015-07-29 at 10 10 59 pm](https://cloud.githubusercontent.com/assets/52581/8955203/ce509806-363e-11e5-9ec7-eed6cab19c8d.png)

**Comment by pippinsplugins** [comment]
What's `Live Demonstration`?

**Comment by sumobi** [comment]
@pippinsplugins possibly a link to your live demo

**Comment by sumobi** [comment]
@pippinsplugins Added some rough text to each feature which will need revising. Any you want removed, or features added?

**Comment by pippinsplugins** [comment]
Let's add one more item to the home page to make it even: https://cloudup.com/cJJE8RKN5vf

How about:

__Member Account Page__

Members can easily view their account history, renew or cancel their membership, and edit their profile from their account details page.

**Comment by pippinsplugins** [comment]
Or:

__Member Emails__

Send welcome emails to new members, email payment receipts, and even remind members before their account expires automatically.

**Comment by sumobi** [comment]
I like even :+1:

**Comment by sumobi** [comment]
Went for member emails.

**Comment by pippinsplugins** [comment]
:+1:
